# Generated by Django 5.0.6 on 2024-05-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=1000)),
                ('requirements', models.CharField(max_length=1000)),
                ('salary', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('date_posted', models.CharField(max_length=1000)),
                ('job_type', models.CharField(max_length=1000)),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
