# Generated by Django 5.0.6 on 2024-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunamis', '0003_remove_job_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
