# Generated by Django 5.0.6 on 2024-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunamis', '0004_job_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='banner',
            field=models.ImageField(blank=True, upload_to='jobs/'),
        ),
    ]
