# Generated by Django 5.0.6 on 2024-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunamis', '0006_alter_job_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
