# Generated by Django 5.0.6 on 2024-05-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunamis', '0007_alter_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
